"""Check one project against the "what not broken means" checklist.

    python tools/verify.py 01_document_scanner
    python tools/verify.py --all

The checklist in docs/58-project-plan.md is prose, and prose gets skimmed once a
project "looks done". Every item below that a machine can decide, it decides.

What this can check
-------------------
* every image the README links to exists, and is not a zero-byte or tiny stub
* the comparison figure exists and has four rows
* every screenshot on disk is referenced, and no two screenshots are near-duplicates
  (the same 35%-of-rows rule ``tools/shoot.py`` applies at capture time, re-applied
  here because a screenshot can be replaced after it was shot)
* the project's tests pass
* ``results/results.json`` exists and was generated by the current code

What this cannot check
----------------------
The last and most important item — *is the finding real* — is a judgement about
whether the README's claim matches the data, and no script decides that. Nor can
it decide whether four samples are four different **kinds** of subject; it only
reports the family tags the run recorded so a human can see them at a glance.
Those two stay manual, which is why they are printed as REVIEW lines rather than
silently passing.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

#: Below this, a PNG is a stub or a failed render rather than a figure.
MIN_FIGURE_BYTES = 8_000
#: Two screenshots agreeing over this fraction of rows are the same picture.
DUPLICATE_PREFIX_LIMIT = 0.35


class Report:
    def __init__(self, project: str) -> None:
        self.project = project
        self.failures: list[str] = []
        self.reviews: list[str] = []
        self.notes: list[str] = []

    def fail(self, msg: str) -> None:
        self.failures.append(msg)

    def review(self, msg: str) -> None:
        self.reviews.append(msg)

    def note(self, msg: str) -> None:
        self.notes.append(msg)

    @property
    def ok(self) -> bool:
        return not self.failures


def _identical_prefix(a: Path, b: Path) -> float:
    import cv2
    import numpy as np

    ia, ib = cv2.imread(str(a)), cv2.imread(str(b))
    if ia is None or ib is None:
        return 0.0
    h = min(ia.shape[0], ib.shape[0])
    w = min(ia.shape[1], ib.shape[1])
    same = 0
    for r in range(h):
        if float(np.abs(ia[r, :w].astype(int) - ib[r, :w].astype(int)).mean()) > 1.0:
            break
        same += 1
    return same / max(ia.shape[0], ib.shape[0])


def check_readme_links(proj: Path, rep: Report) -> None:
    """Every local image and file the README points at must exist and be real."""
    readme = proj / "README.md"
    if not readme.exists():
        rep.fail("no README.md")
        return
    text = readme.read_text(encoding="utf-8")

    for target in re.findall(r"]\(([^)\s]+)\)", text):
        if target.startswith(("http://", "https://", "#", "mailto:")):
            continue
        clean = target.split("#")[0]
        if not clean:
            rep.fail(f"README links to an empty path: `]({target})`")
            continue
        path = (proj / clean).resolve()
        if not path.exists():
            rep.fail(f"README links to a missing file: {clean}")
            continue
        if path.suffix.lower() == ".png" and path.stat().st_size < MIN_FIGURE_BYTES:
            rep.fail(f"{clean} is only {path.stat().st_size} bytes — a stub, not a figure")


def check_results_json(proj: Path, rep: Report) -> None:
    path = proj / "results" / "results.json"
    if not path.exists():
        rep.fail("no results/results.json — run.py has not been run")
        return
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        rep.fail(f"results.json is not valid JSON: {e}")
        return
    if "generated_utc" not in payload:
        rep.fail("results.json has no generated_utc stamp")
    else:
        rep.note(f"results.json generated {payload['generated_utc']}")


def check_screenshots(proj: Path, rep: Report) -> None:
    shots_dir = proj / "results" / "screenshots"
    if not shots_dir.exists():
        rep.fail("no results/screenshots/ — the UI has never been captured")
        return
    shots = sorted(p for p in shots_dir.glob("*.png"))
    if not shots:
        rep.fail("results/screenshots/ is empty")
        return

    readme = (proj / "README.md").read_text(encoding="utf-8") if (proj / "README.md").exists() else ""
    for s in shots:
        rel = f"results/screenshots/{s.name}"
        if rel not in readme:
            rep.fail(f"{rel} is on disk but the README never shows it")
        if s.stat().st_size < 30_000:
            rep.fail(f"{rel} is {s.stat().st_size / 1024:.0f} KB — the page may not have rendered")

    for i in range(len(shots)):
        for j in range(i + 1, len(shots)):
            frac = _identical_prefix(shots[i], shots[j])
            if frac > DUPLICATE_PREFIX_LIMIT:
                rep.fail(
                    f"{shots[i].name} and {shots[j].name} agree over {frac:.0%} "
                    "of the taller image — keep one"
                )
    rep.note(f"{len(shots)} screenshot(s)")


def check_ui(proj: Path, rep: Report) -> None:
    if not (proj / "ui" / "app.py").exists():
        rep.fail("no ui/app.py — every project gets a UI")
        return
    cfg = proj / ".streamlit" / "config.toml"
    if not cfg.exists():
        rep.fail("no .streamlit/config.toml — BaseWeb widgets will use the stock theme")


def check_tests(proj: Path, rep: Report) -> None:
    tests = proj / "tests"
    if not tests.exists():
        rep.fail("no tests/ directory")
        return
    python = REPO / ".venv" / "Scripts" / "python.exe"
    if not python.exists():
        python = Path(sys.executable)
    r = subprocess.run(
        [str(python), "-m", "pytest", str(tests), "-q", "--tb=no", "-p", "no:cacheprovider"],
        cwd=str(REPO),
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        tail = [ln for ln in r.stdout.splitlines() if ln.startswith("FAILED")]
        rep.fail(f"tests fail ({len(tail)}): " + "; ".join(t.split("::")[-1] for t in tail[:6]))
    else:
        last = [ln for ln in r.stdout.splitlines() if "passed" in ln]
        rep.note(f"tests: {last[-1].strip() if last else 'pass'}")


def check_samples_figure(proj: Path, rep: Report) -> None:
    """The comparison figure at the top of the README — four rows, Sr-numbered."""
    candidates = sorted((proj / "docs" / "images").glob("*.png")) if (proj / "docs" / "images").exists() else []
    if not candidates:
        rep.fail("docs/images/ has no figures")
        return
    readme = (proj / "README.md").read_text(encoding="utf-8") if (proj / "README.md").exists() else ""
    # the first image the README shows is the comparison figure
    first = re.search(r"!\[[^\]]*]\((docs/images/[^)\s]+)\)", readme)
    if not first:
        rep.fail("the README shows no comparison figure")
        return
    rep.note(f"comparison figure: {first.group(1)}")


def check_no_ai_footer(proj: Path, rep: Report) -> None:
    readme = proj / "README.md"
    if readme.exists():
        text = readme.read_text(encoding="utf-8")
        for banned in ("Co-Authored-By", "Generated with [Claude", "🤖"):
            if banned in text:
                rep.fail(f"README contains {banned!r}")


def verify(name: str, run_tests: bool = True) -> Report:
    proj = REPO / "projects" / name
    rep = Report(name)
    if not proj.exists():
        rep.fail(f"no such project: {proj}")
        return rep

    check_readme_links(proj, rep)
    check_samples_figure(proj, rep)
    check_results_json(proj, rep)
    check_ui(proj, rep)
    check_screenshots(proj, rep)
    check_no_ai_footer(proj, rep)
    if run_tests:
        check_tests(proj, rep)

    rep.review("are the four samples four different KINDS of subject?")
    rep.review("does every number in the README come from this run?")
    rep.review("is the finding real — does the data actually show it?")
    return rep


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("project", nargs="?", help="folder under projects/")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--no-tests", action="store_true")
    args = ap.parse_args()

    if args.all:
        names = [p.name for p in sorted((REPO / "projects").iterdir()) if p.is_dir()]
    elif args.project:
        names = [args.project]
    else:
        ap.error("give a project name or --all")

    bad = 0
    for name in names:
        rep = verify(name, run_tests=not args.no_tests)
        status = "OK  " if rep.ok else "FAIL"
        print(f"\n{status} {name}")
        for n in rep.notes:
            print(f"       . {n}")
        for f in rep.failures:
            print(f"       X {f}")
        if not rep.ok:
            bad += 1
        elif not args.all:
            for r in rep.reviews:
                print(f"       ? {r}")

    print(f"\n{len(names) - bad}/{len(names)} pass the machine-checkable gates.")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
